###### some data from attitude.cpp
float32 a_input
float32 a_current
float32 a_current_before
float32 a_err			
uint32  flag_wrate
float32 err_u
float32 err_v
float32 err_yaw
####float32 err_u_nominal
####float32 err_v_nominal
float32 err_u_dot
float32 err_v_dot
uint32 flag_lqr_enable
float32 dt
float32 aux2
float32 hz_attitude
uint32  n_iteration
float32 current_yaw
float32 nominal_yaw
float32 current_u
float32 nominal_u
float32 current_v
float32 nominal_v
float32 t_x
float32 t_v
uint32 	flag_t_x
float32 pos_x
float32 pos_y
float32 pos_z
float32 rotateangle_nominal
float32 rotateangle_current
float32 dt_sensor
float32 hz_sensor
float32 flag_controlstate
float32 flag_sensor
######  float32 dt_controlstate
######  float32 hz_controlstate

float32 bodyratesp_x
float32 bodyratesp_x_original
float32 bodyratecur_x
float32 bodyratesp_y
float32 bodyratesp_y_original
float32 bodyratecur_y
float32 bodyratesp_z
float32 bodyratesp_z_original
float32 bodyratecur_z
float32 bodyrateerr_x
float32 bodyrateerr_y
float32 bodyrateerr_z
float32 vratesp_x
float32 vratesp_y
float32 vratesp_z
float32 uvwratesp_x
float32 uvwratesp_y
float32 uvwratesp_z
float32 vrate_x
float32 vrate_y
float32 vrate_z
float32 uvwrate_x
float32 uvwrate_y
float32 uvwrate_z
float32 vrateerr_x
float32 vrateerr_y
float32 vrateerr_z
float32 uvwrateerr_x
float32 uvwrateerr_y
float32 uvwrateerr_z

float32 a01
float32 a02
float32 a03
float32 a04

float32 a11
float32 a12
float32 a13
float32 a14

float32 a21
float32 a22
float32 a23
float32 a24

float32 a31
float32 a32
float32 a33
float32 a34

float32 b11
float32 b12
float32 b13
float32 b14

float32 b21
float32 b22
float32 b23
float32 b24

float32 b31
float32 b32
float32 b33
float32 b34

float32 r01
float32 r02
float32 r03
float32 r04

float32 r11
float32 r12
float32 r13
float32 r14

float32 r21
float32 r22
float32 r23
float32 r24

float32 r31
float32 r32
float32 r33
float32 r34

float32 s11
float32 s12
float32 s13
float32 s14

float32 s21
float32 s22
float32 s23
float32 s24

float32 s31
float32 s32
float32 s33
float32 s34

float32 norma0
float32 norma1
float32 normb1
float32 norma2
float32 normb2
float32 norma3
float32 normb3

float32 r0_check_1
float32 r0_check_2
float32 r0_check_3
float32 r0_check_4


float32 compensation_1
float32 compensation_2
float32 compensation_3
float32 compensation_4